public class Calculator {
   Integer c;
    
    public integer Calculator(){
        
        return c;
    }
    
    public void Addition( Integer a,Integer b){
       
        c = a+b;
        system.debug('Print c: '+c);
    }

    Public void subtract(Integer a, integer b){
        
        c = a-b;
        system.debug('Print c: '+c);
    }
    
     public void Multiply( Integer a,Integer b){
       
        c = a*b;
        system.debug('Print c: '+c);
    }
    
     public void Devision( Integer a,Integer b){
       
        double c = a/b;
        system.debug('Print c: '+c);
    }
}