public class printPattern {

    public static void printPatternNew(integer n){
        for(integer row =1; row<n; row++){
            string s=' ';
            //system.debug(s1);
            for(integer col=1; col<=row; col++ ){
                
                s = s+' * ';
               
                
            }
           // s='*';
          system.debug(s) ;
            
            
    }
  }
}